### ISSUE TITLE
Bump proc macros 2 module to latest version

### ISSUE THREAD

**Issue by tirkarthi** [rust-num/num-derive#13]
Bug report : 

There was a recent change in proc macros 1.2 API that made some breaking changes. It broke proc macros 2 with version 0.3.8 on some projects. So I tried running this project against latest nightly and it works which should have caused an error during compilation of proc macros 2 module.

Upstream rustc issue reference : https://github.com/rust-lang/rust/pull/50473#issue-186182501
Upstream proc macros 2 PR (merged) : https://github.com/alexcrichton/proc-macro2/pull/90
Successful Nightly build with 0.3.8 compilation : https://travis-ci.org/tirkarthi/num-derive/jobs/382026352

Failure of proc macros 0.3.8 compilation in Rocket : https://travis-ci.org/SergioBenitez/Rocket/jobs/381529609#L527
proc macros 2 v0.4.3 released with the changes. Ref : https://github.com/alexcrichton/proc-macro2/tree/0.4.3

Feel free to close this if it's irrelevant or I am missing something.

Thanks

**Comment by cuviper** [comment]
I _suspect_ those changes are only a problem if you enable nightly/unstable features in proc-macro2.  Since we don't do that here, it's still building fine.  Regardless, I'll look into updating syn/quote/proc-macro2 to their latest releases.

**Comment by cuviper** [comment]
num-derive 0.2.2 is published with updated dependencies.
