### ISSUE TITLE
derives panic when a discriminant is given by a macro

### ISSUE THREAD

**Issue by AdnoC** [rust-num/num-derive#16]
If you use set the discriminant of a C-like enum with a macro the derive panics. This happens with both `ToPrimitive` and `FromPrimitive`.

Minimal example:

```rust
#[macro_use]
extern crate num_derive;
extern crate num_traits;

macro_rules! get_an_isize {
    () => (0_isize)
}

#[derive(FromPrimitive)]
pub enum CLikeEnum {
    VarA = get_an_isize!(), // panics
    VarB = 2,
}
```

Errors with

```
error: proc-macro derive panicked
 --> src\lib.rs:9:10
  |
9 | #[derive(FromPrimitive)]
  |          ^^^^^^^^^^^^^
  |
  = help: message: called `Result::unwrap()` on an `Err` value: ParseError(Some("failed to parse derive input: failed to parse"))
```

Cargo.toml:

```
[dependencies]
num-traits = "0.2"
num-derive = "0.2"
```

Rust version:
`rustc 1.27.0 (3eda71b00 2018-06-19)`

**Comment by AdnoC** [comment]
Actually, seems like it is `syn`'s fault, as `syn::parse` is returning an `Err`.

**Comment by cuviper** [comment]
You may need to enable the "full-syntax" feature here, which enables "syn/full".

**Comment by AdnoC** [comment]
Yeah, just figured that out. Going to make a ticket for `syn` since it should be able to parse valid custom derive input.

**Comment by bcantrill** [comment]
I hit this as well -- thank you @AdnoC and @cuviper for what ended up being a quick fix to an otherwise vexing problem!  Was there ever an issue open on `syn`? If not, I think I'd like to get an issue open over there (and/or commented upon); the failure mode here is pretty brutal...

**Comment by cuviper** [comment]
@bcantrill I don't know if there was ever a `syn` issue, but the error now seems worse:

```
error: proc-macro derive panicked
 --> src/lib.rs:9:10
  |
9 | #[derive(FromPrimitive)]
  |          ^^^^^^^^^^^^^
  |
  = help: message: called `Result::unwrap()` on an `Err` value: Error("expected `,`")
```

I guess it's sort of more specific than "failed to parse", but there's not enough context to really be useful.

Maybe instead of `syn::parse(input).unwrap()`, we should try the [`syn::parse_macro_input!` macro](https://docs.rs/syn/1.0.36/syn/macro.parse_macro_input.html). If that prints span info, it will be a lot more helpful. Or maybe we can manually do the same while [combining](https://docs.rs/syn/1.0.36/syn/struct.Error.html#method.combine) a message about the "full-syntax" feature.

**Comment by cuviper** [comment]
Re-opening since I think we can indeed do better on `num-derive`'s part.

I have it looking like this now:

```
error: expected `,`
  --> src/test.rs:12:24
   |
10 |     VarA = get_an_isize!(), // panics
   |                        ^

error: this might need the "full-syntax" feature of `num-derive`
  --> src/test.rs:12:24
   |
10 |     VarA = get_an_isize!(), // panics
   |                        ^

error: aborting due to 2 previous errors
```

But I'd like to connect the second message back to the `derive(FromPrimitive)` span if possible.

**Comment by cuviper** [comment]
Aha, `Span::call_site()` is what I want. I'll get a PR up shortly, once I figure out how to test this...

**Comment by bcantrill** [comment]
Thanks for opening this back up!  The failure mode was indeed really confusing -- but your new error message is great, and would have sent me to the right spot more or less immediately; thanks again!
