### ISSUE TITLE
Provide optional inline hint

### ISSUE THREAD

**Issue by pczarn** [rust-num/num-derive#33]
In my functions, {To,From}Primitive is not getting inlined. The only workaround is implementing them myself with `#[inline]` added.

**Comment by cuviper** [comment]
I think for all of the newtype derives, we probably want `#[inline]` always.

For enum derives, it's less clear -- inlining is probably good for small or medium size enums, but could hurt for large enums. I suppose it's still just a hint to LLVM though, not `#[inline(always)]`, so I suppose the risk is mostly just to compile times.
