### ISSUE TITLE
Version 0.1.42 breaks code with #![deny(trivial_numeric_casts)]

### ISSUE THREAD

**Issue by Pzixel** [rust-num/num-derive#6]
Minimal reproducible example

Cargo.toml

```
[dependencies]
num = "0.1"
num-derive = "0.1"
```

main.rs
```rust
#![deny(trivial_numeric_casts)]
extern crate num;
#[macro_use]
extern crate num_derive;

#[derive(FromPrimitive)]
pub enum SomeEnum {
    A = 1
}

fn main() {

}
```

Error:
```
   Compiling hello_world_clion v0.1.0 (file:///C:/Users/Alex/Documents/Rust/hello_world_clion)
error: trivial numeric cast: `isize` as `isize`. Cast can be replaced by coercion, this might require type ascription or a temporary variable
 --> src\main.rs:6:10
  |
6 | #[derive(FromPrimitive)]
  |          ^^^^^^^^^^^^^
  |
note: lint level defined here
 --> src\main.rs:1:9
  |
1 | #![deny(trivial_numeric_casts)]
  |         ^^^^^^^^^^^^^^^^^^^^^

error: aborting due to previous error
```

Our project depends heavily on this `deny` attribute so disable it is a no-no. Currently we use `num-derive = "=0.1.41"` but I hope we can switch to higher version. Is seems to be an easy fix.

**Comment by cuviper** [comment]
Sure, we can probably just add `#[allow(trivial_numeric_casts)]` in the derived code.  Care to send a PR?
(and make sure we test with that `deny` somewhere too)

**Comment by Pzixel** [comment]
This deny is useful so I think we may just tune the macro a bit, instead of `a as Foo` it could just generate `let a_as_foo: Foo : a`. And it's safer than `allow` directive.

**Comment by cuviper** [comment]
You're welcome to experiment with different approaches, of course.

**Comment by Pzixel** [comment]
Ok, I can try. However, I'm not really familiar with macros because I'm new in rust and I just wanted my code to compile 😄 , but the whole last month I'm just fixing issues one by one in my dependencies... And this one seems to be really hard. Any help about how can I debug macro or something? Because I have no idea how to do it.

**Comment by cuviper** [comment]
I went ahead and allowed the warning in #7, if you'd like to test it on your code.  We can followup with a different approach if you figure out something better.

Debugging macros is kind of a pain.  On nightly rustc, you can use `rustc --pretty=expanded` to see what gets derived.  There's also `-Ztrace-macros` and `-Zdebug-macros`, but I think those are only for `macro_rules!`.
