### ISSUE TITLE
Future incompatibility with Rust RFC 3373: Avoid non-local definitions in functions

### ISSUE THREAD

**Issue by Urgau** [rust-num/num-derive#60]
Rust [RFC 3373: Avoid non-local definitions in functions](https://github.com/rust-lang/rfcs/pull/3373) was accepted and it's implementation at https://github.com/rust-lang/rust/pull/120393 found that this crate would be affected by it.

To be more precise users of this crate would be affected by it, in the form of a warn-by-default lint. This is because the derive macros from this crate use `impl` in a local context, `const _IMPL_NUM_???_FOR_???`:

https://github.com/rust-num/num-derive/blob/50ecdb10ac0934eccd971c20bde9bee5fe99ed98/src/lib.rs#L102-L109

Fortunately a simple fix exist for this crate, by using a const-anon instead of named one:
```diff
 fn dummy_const_trick(trait_: &str, name: &Ident, exp: TokenStream2) -> TokenStream2 {
-    let dummy_const = Ident::new(
-        &format!("_IMPL_NUM_{}_FOR_{}", trait_, unraw(name)),
-        Span::call_site(),
-    );
    quote! {
        #[allow(non_upper_case_globals, unused_qualifications)]
-        const #dummy_const: () = {
+        const _: () = {
```

-------

I would suggest applying some form of the patch above as well as releasing a patch version of this crate, as to have a fix available for users as soon as possible.

cc @cuviper

**Comment by cuviper** [comment]
Ok, I'll get to this soon - thanks for the heads up!

**Comment by cuviper** [comment]
`num-derive v0.4.2` should be fixed for this.

**Comment by Urgau** [comment]
Great, thks for fixing it @cuviper.
